# Generated by Django 4.1.2 on 2022-10-20 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_user_surname_alter_user_avatar_alter_user_bio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('logo', models.ImageField(default='avatar.svg', null=True, upload_to='', verbose_name='logo')),
            ],
        ),
    ]
