# Generated by Django 4.1.2 on 2022-10-20 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_suport_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='imagem'),
        ),
    ]
